

export const environment = { 
    REST_API : 'http://api.appkey.io',
    APP_TOKEN:'APPKEY_APP_TOKEN',
    GOOGLE_CLIENT_ID: 'GOOGLE_ID_FOR_WEBSITE',
    APPLE_BUNDLE_ID:'APPLE_BUNDLE_ID',
    APPLE_REDIRECT_URI:'APPLE_LOGIN_REDIRECT_URL'
  };